name: update-releases
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 17 * * MON' # 5PM Monday UTC (10AM Monday PST) - Set to 2hrs after react-native-windows publish starts
jobs:
  check-bats-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all branches etc
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      # Clean up some unneeded disk hogs
      - run: Remove-Item "$Env:Programfiles\Boost" -Recurse -Force -ErrorAction SilentlyContinue -ErrorVariable err
      - run: Write-Host $err
      - run: Remove-Item "$Env:Programfiles\Unity" -Recurse -Force -ErrorAction SilentlyContinue -ErrorVariable err
      - run: Write-Host $err
      - run: git config --global user.email "30809111+acoates-ms@users.noreply.github.com"
      - run: git config --global user.name "Andrew Coates"
      - run: npm install semver
      - run: node generate-all.js
      - run: git add RELEASES
      - run: git commit -m "Update RELEASES"
      - run: git push

  check-bats-mac:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all branches etc
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      # Clean up some unneeded disk hogs
      - run: Remove-Item "$Env:Programfiles\Boost" -Recurse -Force -ErrorAction SilentlyContinue -ErrorVariable err
      - run: Write-Host $err
      - run: Remove-Item "$Env:Programfiles\Unity" -Recurse -Force -ErrorAction SilentlyContinue -ErrorVariable err
      - run: Write-Host $err
      - run: git config --global user.email "30809111+acoates-ms@users.noreply.github.com"
      - run: git config --global user.name "Andrew Coates"
      - run: npm install semver
      - run: node generate-all-mac.js
      - run: git add RELEASES_MAC
      - run: git commit -m "Update RELEASES_MAC"
      - run: git push
