name: update-releases
on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 17 * * MON' # 5PM Monday UTC (10AM Monday PST) - Set to 2hrs after react-native-windows publish starts
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all branches etc
      - uses: actions/setup-node@v1
      - run: git config --global user.email "30809111+acoates-ms@users.noreply.github.com"
      - run: git config --global user.name "Andrew Coates"
      - run: node generate-all.js
      - run: git add *
      - run: git push